on:
  push:
    tags:
      - "*"

name: CI # Continuous Integration

jobs:
  lint:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout ğŸ›ï¸
      - uses: dtolnay/rust-toolchain@stable
        name: Setup Cargo Toolchain ğŸ›ï¸
      - name: Running Tests ğŸš€
        run: cargo test --all-features
      - name: Check Code Format ğŸ”§
        run: cargo fmt -- --check
      - name: Lint with Clippy ğŸ”§
        run: cargo clippy --all-targets --all-features -- -D warnings
  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout ğŸ›ï¸
      - uses: dtolnay/rust-toolchain@stable
        name: Setup Cargo Toolchain ğŸ›ï¸
      - name: Build ğŸ”§
        run: cargo build --release --all-features
      - name: Run ğŸ”§
        run: cargo run --release
      - uses: actions/upload-artifact@v4
        name: Upload Artifacts ğŸš€
        with:
          name: output
          path: output/
